name: Update Debian Repository

on:
  workflow_dispatch:
  push:
    paths:
      - 'packages/*.deb'

jobs:
  update-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Import GPG key and setup gpg-agent
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --import --batch
          echo "allow-preset-passphrase" > ~/.gnupg/gpg-agent.conf
          gpg-connect-agent reloadagent /bye
          /usr/lib/gnupg2/gpg-preset-passphrase --preset "${{ secrets.GPG_KEY_ID }}" <<< "$GPG_PASSPHRASE"

      - name: Generate Packages and Release files
        run: |
          mkdir -p public/dists/stable/main/binary-arm64
          dpkg-scanpackages --arch arm64 packages > public/dists/stable/main/binary-arm64/Packages
          gzip -k -f public/dists/stable/main/binary-arm64/Packages
          
          cd public/dists/stable
          
          cat << EOF > Release
          Origin: https://deeepkk.github.io/apt
          Label: Droidian PKG
          Suite: stable
          Codename: stable
          Version: 1.0
          Architectures: arm64
          Components: main
          Description: Droidian Packages 
          EOF
          
          apt-ftparchive release . >> Release
          gpg --clearsign --batch --yes -o InRelease Release
          gpg -abs --batch --yes -o Release.gpg Release
        env:
          GPG_TTY: $(tty)

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_orphan: true
